### ISSUE TITLE
new data prediction

### ISSUE THREAD

**Issue by InaKhandelwal** [roopalgarg/lstm-tensorflow#1]
I am not able to predict the new unseen data using this model.

**Comment by roopalgarg** [comment]
The current architecture is meant for classification based tasks, sentiment in this case. 
To use the core LSTM code and use it to be predict unseen text, ie, for text generation, you would have to change the training method to predict next word given the previous context.
In practice, you would have to stack multiple layers (3 worked for me in the past) to get it to work.
Check the code in the [chatbot repo](https://github.com/roopalgarg/chatbot).
